
import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar";
import Header from "@/components/layout/Header";
import { ThemeProvider } from "next-themes";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`h-full overflow-hidden bg-gray-100 antialiased dark:bg-gray-700 dark:text-white`}
      >
        <ThemeProvider enableSystem={true} attribute="class">
        <div className="flex flex-col h-screen">
        {/* <Header /> */}
        <div className="flex gap-0 flex-row overflow-hidden">
        <Sidebar />
        <main className="w-full h-full p-4 pb-0 overflow-y-auto">
          {children}
        </main>
        </div>
        </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
